version: "3"

services:

  api:
    env_file:
      - .env
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    container_name: go-mux-api
    ports:
      - "8020:8020"
    depends_on:
      - postgres-db

  postgres-db:
    env_file:
      - .env
    build:
      context: ./postgres-db
      dockerfile: Dockerfile
    container_name: api-db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
