apiVersion: v1
kind: Service
metadata:
  name: go-mux-api-lb
spec:
  type: LoadBalancer
  loadBalancerIP: 34.105.121.217
  selector:
    app: go-mux
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8010
